openapi: 3.0.2
info:
  title: API for compile server
  description: "GET request return the version of given compiler (interpreter), \n\
    POST request requires an UUID of user from Firebase Authentication\n"
  version: 1.0.0-oas3
servers:
- url: https://online-code-exercise.herokuapp.com
paths:
  /csharp:
    summary: Access to C# compiler
    get:
      summary: Return output of command <pre>dotnet --info</pre>
      responses:
        "500":
          description: Unexpected error
        "200":
          description: .NET CORE SDK info and its runetime enviroment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
    post:
      summary: Test C# code
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestData'
            example:
              code: using System;namespace sample\n{class Program\n{static void Main(string[]args)\n{string
                input=Console.ReadLine();string keyword=Console.ReadLine();Console.WriteLine(input.IndexOf(keyword));}}}
              testcases:
              - input: |-
                  Hello
                  e
                ouput: "1"
              - input: |-
                  World
                  @
                output: -1
        required: true
      responses:
        "200":
          description: Code was compiled or run successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalyzedData'
              example:
              - total: 2
                passed: 1
                failed: 1
                failedIndexes:
                - 0
                results:
                - passed: false
                  input: |-
                    Hello
                    e
                  expected: "1"
                  actual: "2"
                - passed: true
                  input: |-
                    World
                    @
                  expected: -1
        "400":
          description: The test failed to compile or had syntax error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShellError'
      security:
      - BearerAuth: []
  /py3:
    summary: Access to python3
    get:
      summary: return version of python3
      responses:
        "200":
          description: Return output of command <pre>python3 --version</pre>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "500":
          description: Unexpected error
    post:
      summary: Test python code
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestData'
            example:
              code: line1 = input()\nline2 = input()\nprint(line1)\nprint(line2)
              testcases:
              - input: |-
                  a
                  b
                ouput: |-
                  a
                  b
              - input: |-
                  a

                  b
              - output: |
                  a
        required: true
      responses:
        "400":
          description: Code failed to run
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShellError'
        "200":
          description: Code run successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalyzedData'
              example:
                total: 2
                passed: 1
                failed: 1
                failedIndexes:
                - 1
                results:
                - passed: true
                  input: |-
                    a
                    b
                  expected: |-
                    a
                    b
                - passed: false
                  input: |-
                    a

                    b
                  expected: |
                    a
                  actual: a
      security:
      - BearerAuth: []
  /java:
    summary: Access to java compiler
    get:
      summary: return java and javac version
      responses:
        "200":
          description: Return the output of command <pre>java -version</pre>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
        "500":
          description: Unexpected Error
    post:
      summary: Test code with given input and expected output
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestData'
            example:
              code: import java.util.Scanner;public class Program{public static void
                main(String[]args){Scanner reader=new Scanner(System.in);int a=reader.nextInt();int
                b=reader.nextInt();System.out.println(a+b);reader.close();}}
              testcases:
              - input: 1 2
                output: "3"
        required: true
      responses:
        "200":
          description: Code was compiled or run successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalyzedData'
              example:
                total: 1
                passed: 1
                failed: 0
                results:
                - passed: true
                  input: 1 2
                  expected: "3"
        "400":
          description: The test failed to compile or had syntax error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShellError'
      security:
      - BearerAuth: []
components:
  schemas:
    ShellError:
      properties:
        name:
          type: string
          description: an error type, which is usually a shell error
          example: ChildProcessError
        code:
          type: integer
          description: |
            Exit code, [see this Stackoverflow answer](https://unix.stackexchange.com/a/254747)
          example: 1
        childProcess:
          type: object
          description: this object is not used
          example: {}
        stdout:
          type: string
          description: output written to stdout stream, always an empty string
          example: ""
        stderr:
          type: string
          description: error message written to stderr stream
    TestData:
      required:
      - code
      - testcases
      properties:
        code:
          type: string
          description: The code to test
        testcases:
          type: array
          description: Contains serveral test cases which will be used to test the
            given code
          items:
            $ref: '#/components/schemas/TestData_testcases'
    TestResult:
      required:
      - expected
      - input
      - passed
      properties:
        passed:
          type: boolean
          description: whether the test is passed or not
        input:
          type: string
          description: The content passed into stdin stream
        expected:
          type: string
          description: The expected output
        actual:
          type: string
          description: |
            The content which program wrote to stdout stream,
             must be present if the test failed
    AnalyzedData:
      required:
      - failed
      - passed
      - results
      - total
      properties:
        total:
          type: integer
          description: The total number of test cases
        passed:
          type: integer
          description: The number of tests passed
        failed:
          type: integer
          description: The number of tests failed
        failedIndexes:
          type: array
          description: The positions of failed tests, must be present if there are
            any failed tests
          items:
            type: integer
        results:
          type: array
          description: The result of each test
          items:
            $ref: '#/components/schemas/TestResult'
    inline_response_200:
      type: object
      properties:
        message:
          type: string
          example: |
            .NET Core SDK (reflecting any global.json):\n
             Version:   3.1.405\n
              Commit:    65f9d75b1c\n\n
              Runtime Environment:\n
               OS Name:     debian\n
                OS Version:  10\n
                 OS Platform: Linux\n
                  RID:         debian.10-x64\n
                   Base Path:   /root/.dotnet/sdk/3.1.405/\n\n
                   Host (useful for support):\n
                     Version: 3.1.11\n
                       Commit:  f5eceb8105\n\n
                       .NET Core SDKs installed:\n
                         3.1.405 [/root/.dotnet/sdk]\n\n
                         .NET Core runtimes installed:\n
                           Microsoft.AspNetCore.App 3.1.11 [/root/.dotnet/shared/Microsoft.AspNetCore.App]\n
                             Microsoft.NETCore.App 3.1.11 [/root/.dotnet/shared/Microsoft.NETCore.App]\n\n
                             To install additional .NET Core runtimes or SDKs:\n
                               https://aka.ms/dotnet-download\n
    inline_response_200_1:
      type: object
      properties:
        message:
          type: string
          example: Python 3.8.5
    inline_response_200_2:
      type: object
      properties:
        message:
          type: string
          example: "openjdk version \"11.0.9.1\" 2020-11-04\nOpenJDK Runtime Environment\
            \ (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)\nOpenJDK 64-Bit Server VM (build\
            \ 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing) , \n"
    TestData_testcases:
      required:
      - input
      - ouput
      type: object
      properties:
        input:
          type: string
          description: The content to pass into stdin stream
        output:
          type: string
          description: The content expected to be written to stdout stream
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
